# Tarea día 8
**Programación I**   

## ***Byron Ajanel***

In [1]:
import numpy as np

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [3]:
"Forma A"
n=4
m=4
d = np.floor ( 2 * np.random.random ((int(n)  , int(m) )))
e= np.floor ( 2 * np.random.random (( int(n) , int(m) )))
f=(np.insert(d, d.shape[1], (e), 1))
f.resize((5,5))
f

array([[0., 0., 1., 1., 0.],
       [1., 1., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [4]:
" Forma B"

fila=8
columna=8
ceros=np.zeros(fila*columna)
m=np.arange(64)

matriz=np.random.choice(m, int((8*8)/2), replace=False)
ceros[matriz]=1
ceros.resize((8,8))
ceros

array([[0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 1., 0., 0.],
       [1., 0., 1., 1., 0., 1., 1., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 



In [5]:
ceros=np.zeros([5,2])
ceros.resize((10,1))
print("Matriz de Ceros")
print(ceros)

print("......................")

print("Matriz de unos")
unos=np.ones([5,2])
unos.resize((10,1))
print (unos)

Matriz de Ceros
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
......................
Matriz de unos
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


2.	Apile ambos vectores a lo largo de una tercera dimensión. 


In [6]:
a=np.dstack((ceros,unos))
print(a)

[[[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]]



3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 

In [256]:
unos.resize((1,10))
unos

ceros.resize((1,10))
ceros

a=np.concatenate((ceros,unos))
a.resize((20,1))
print(a)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 


In [92]:
n=6
var = np.random.randint(6, size=(n, 3))
var

array([[4, 1, 1],
       [3, 3, 4],
       [1, 1, 4],
       [4, 0, 4],
       [1, 4, 4],
       [2, 3, 0]])

2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [263]:
def f(x):
    
    return 2*var[0:n,0]+3*var[0:n,1]+var[0:n,2]**2

f(var)

array([70, 16, 79, 61, 86, 47, 80, 50, 45, 55])

In [262]:
def f(x,y,z):
    return 2*x+3*y+z**2

b = np.fromfunction(f, (3,1,5), dtype=int)
b

array([[[ 0,  1,  4,  9, 16]],

       [[ 2,  3,  6, 11, 18]],

       [[ 4,  5,  8, 13, 20]]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [150]:
# Metódo Monte Carlo 

Area_gde = np.random.randint(0,2, size=(50,50)) 

Area_peq = Area_gde[30: , 0:20]

Resultado=(50*50*sum(sum(Area_peq))/sum(sum(Area_gde)))

print("El resultado estimado del área es ",  + Resultado)



El resultado estimado del área es  398.69029275808936


## Ejercicio 5

### *Tarea*

## 1. 
1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

# Se encuentra hasta abajo del documento   


## 2.  
2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)

In [109]:
# Archivo binario .npy

Ajanel_Byron = np.random.randint(0,10,[5,5])

# Para guardarlo utilizamos la ruta y la extensin .npy

np.save('Ajanel_Byron.npy', Ajanel_Byron)

# Y lo cargamos de nuevo
Ajanel_Byron = np.load('Ajanel_Byron.npy')

Ajanel_Byron

array([[3, 5, 9, 7, 2],
       [4, 5, 2, 4, 8],
       [7, 3, 9, 1, 6],
       [1, 1, 0, 8, 2],
       [7, 2, 4, 8, 7]])

In [120]:
# Archivo binario .npz

Ajanel_3 = np.random.randint(0,10,[5,5])

# Utilizaremos savez para guardar de forma comprimida con la extensión .npz

# Especificaremos un nombre para la matriz que queramos guardar (Ajanel_3)

np.savez('Ajanel_3.npz', Ajanel_3=Ajanel_3)

# Y los cargamos de nuevo

Ajanel_3 = np.load('Ajanel_3.npz')
Ajanel_3

   
## 3. 
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)

In [80]:
"""
Funcion que guarda los arreglos de un archivo de texto:
"""
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],np.int32)
np.savetxt("Tarea_8.txt",x)

"""
Funcion que carga los arreglos de un archivo de texto:
"""

np.loadtxt("Tarea_8.txt")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

## 4. 
Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [81]:
n=10
variables = np.random.randint(80, size=(n, 7))
variables

array([[68, 40, 17, 68, 40, 41, 28],
       [44, 65,  1, 79, 79, 11, 73],
       [24, 37, 16, 57, 13,  2, 69],
       [56, 48, 70, 53, 48,  9, 17],
       [50, 44,  6, 69,  5, 20, 41],
       [27, 33, 12, 33, 58, 28, 14],
       [50, 66, 28, 78,  9, 47, 79],
       [46, 35, 41, 46, 44, 18,  5],
       [68, 25, 59,  2, 59, 55, 54],
       [12, 70,  1, 30, 29,  5, 56]])

In [281]:
np.savetxt("estimacionMCO.csv", variables, delimiter=' ', fmt='%d')

In [284]:
def estimacionMCO(datos):
    return np.loadtxt("estimacionMCO.csv", delimiter=',', skiprows=1)

In [ ]:
datos=1
estimacionMCO(datos)

# Respuestas de las 73 "Funciones"

## Rutinas de creación de matrices ¶

In [46]:
""""
1 numpy.empty
"""

a=np.empty([2, 2])
print(a)

[[1.30388024e-076 5.04050503e+223]
 [1.87725413e-009 5.23394038e+180]]


In [45]:
"""
2 a is array-like
"""

a = ([1,2,3], [4,5,6])                         
b= np.empty_like(a)
print(b)

[[3602    0    0]
 [   0    0    0]]


In [39]:
""""
3 Creación de Matrices"
"""

x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
""""
3 Creación de Matrices de unos"
"""

a=np.ones((5,3))
a


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
""""
4 numpy.zeros¶
""""

a=np.zeros((5,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
""""
5 numpy.full
"""
a= np.full((2, 2), np.inf)
a

array([[inf, inf],
       [inf, inf]])

In [50]:
"""
6 numpy.eye
"""

a=np.eye(2, dtype=int)
a

array([[1, 0],
       [0, 1]])

In [51]:
"""
7 
numpy.identity
"""
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
"""
8 
numpy.full_like
"""
x = np.arange(6, dtype=int)
a=np.full_like(x, 1)
a


array([1, 1, 1, 1, 1, 1])

In [67]:
"""
9 
numpy array Más de una dimensión:
"""
a= np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [72]:
"""
10 
Crear una matriz a partir de subclases:
"""
a=np.array(np.mat('1 8 7; 3 9 10; 2 5 19'))
a

array([[ 1,  8,  7],
       [ 3,  9, 10],
       [ 2,  5, 19]])

In [82]:
"""
11 
Convierta una lista en una matriz:
"""

a = [1, 2, 4,  3, 7, 4, 8, 5]
b=np.asarray(a)
b

array([1, 2, 4, 3, 7, 4, 8, 5])

In [88]:
"""
12 
numpy.ascontiguousarray
"""

x = np.arange(6).reshape(2,3)
a= np.ascontiguousarray(x, dtype=np.float32) 
a

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [89]:
"""
13 
numpy.asmatrix
interprete la entrada como una matriz.
"""
x = np.array([[1, 2], [3, 4]])

m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

In [92]:
"""
14 numpy.copy
"""

x = np.array([1, 2, 3])
y = x
z = np.copy(x)

#Tenga en cuenta que, cuando modificamos los cambios x, y, pero no z:

x[0] = 10
print(x[0] == y[0])
print (x[0] == z[0])


True
False


In [95]:
""" 
15 
numpy.frombuffer
"""

s = b'hello world dato'
a=np.frombuffer(s, dtype='S1', count=5, offset=6)
a

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

In [96]:
"""
16 
numpy.fromfile
"""

dt = np.dtype([('time', [('min', np.int64), ('sec', np.int64)]),('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10; x['temp'] = 98.25
x

array([((10, 0), 98.25)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [98]:
""" 
17 
numpy.fromfunction
""""

a=np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [99]:
"""
18 
numpy.fromfunction usando lambda
"""

a= np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [100]:
"""
19 numpy.fromiter
"""
b= iterable = (x*x for x in range(5))
a= np.fromiter(iterable, float)
a

array([ 0.,  1.,  4.,  9., 16.])

In [105]:
"""20 
numpy.fromstring( string , dtype = float , count = -1 , sep = '' ) 
Una nueva matriz 1-D inicializada a partir de datos de texto en una cadena.
"""
a=np.fromstring('1, 2', dtype=int, sep=',')
a

array([1, 2])

In [110]:
"""
21 
numpy.loadtxt 
"""
from io import StringIO   # La cadena se comporta como un objeto de archivo
c = StringIO(u"0 1\n2 3")
a=np.loadtxt(c)
print(a)

[[0. 1.]
 [2. 3.]]


In [111]:
d = StringIO(u"M 21 72\nF 35 58")
b= np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),'formats': ('S1', 'i4', 'f4')})
print(b)

[(b'M', 21, 72.) (b'F', 35, 58.)]


In [115]:
""" 
22 
numpy.core.records.fromarrays
"""

x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')

print(r[1])

x1[1]=34
c=r.a
print(c)

(2, 'dd', 2.)
[1 2 3 4]


## Crear matrices de Carácteres

In [130]:
"""
23 
numpy.char.capitalize 
"""
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c

otra forma 

a= np.char.capitalize(c)
print(c)
print(a)

[b'a1b2' b'1b2a' b'b2a1' b'2a1b']
[b'A1b2' b'1b2a' b'B2a1' b'2a1b']


In [138]:
"""
24 
numpy.char.encode 
"""
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
print(c)
print("........................")
d=np.char.encode(c, encoding='cp037')
print(d)

['aAaAaA' '  aA  ' 'abBABba']
........................
[b'\x81\xc1\x81\xc1\x81\xc1' b'@@\x81\xc1@@'
 b'\x81\x82\xc2\xc1\xc2\x82\x81']


In [139]:
"""
25 
numpy.char.lower 
"""

c = np.array(['A1B C', '1BCA', 'BCA1']); c

a= np.char.lower(c)
a

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [143]:
""" 
26 
numpy.char.swapcase 
Devuelve una copia de la cadena con elementos en mayúscula convertidos a minúsculas y viceversa.
"""
c=np.array(['a1B c','1b Ca','b Ca1','cA1b'])

a= np.char.swapcase(c)
a

array(['A1b C', '1B cA', 'B cA1', 'Ca1B'], dtype='<U5')

In [145]:
"""
27 
numpy.char.chararray 
Proporciona una vista conveniente de las matrices de cadenas y valores unicode.
"""

charar = np.chararray((3, 3))
charar[:] = 'a'
charar

chararray([[b'a', b'a', b'a'],
           [b'a', b'a', b'a'],
           [b'a', b'a', b'a']], dtype='|S1')

## Rutinas de manipulación de matrices

In [151]:
"""
28 
numpy.shape( a ) 
Devuelve la forma de una matriz
"""

a = np.array([(1, 2), (3, 4)])
b=np.shape(a)

x=a.shape
print(b)
print(x)

(2, 2)
(2, 2)


In [153]:
"""
29 
numpy.reshape( a , newshape , order = 'C' ) 
Da una nueva forma a una matriz sin cambiar sus datos.
"""

a = np.array([[1,2,3], [4,5,6]])
b = np.reshape(a, 6)

c = np.reshape(a, 6, order='F')
print(a)
print(b) 
print (c)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [158]:
"""
30 
numpy.ravel( a , orden = 'C' ) 
Devuelve una matriz aplanada contigua.
"""

x = np.array([[1, 2, 3], [4, 5, 6]])
a= np.ravel(x)
print(x)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [160]:
"""
31 
numpy.ndarray.flat 
Esta es una numpy.flatiterinstancia, que actúa de manera similar a, 
pero no es una subclase del objeto iterador incorporado de Python.
"""

x.flat = 3; x


array([[3, 3, 3],
       [3, 3, 3]])

In [163]:
x.flat[[1,4]] = 1;x 

array([[3, 1, 3],
       [3, 1, 3]])

In [165]:
"""
32 
numpy.moveaxis 
Mueva los ejes de una matriz a nuevas posiciones.
Otros ejes permanecen en su orden original.
"""

x = np.zeros((3, 4, 5))
a= np.moveaxis(x, 0, -1).shape

b= np.moveaxis(x, -1, 0).shape
print(a)
print(b)

(4, 5, 3)
(5, 3, 4)


In [171]:
"""
33 
numpy.rollaxis( a , axis , start = 0 ) 
Gire el eje especificado hacia atrás, hasta que se encuentre en una posición determinada.
"""

a = np.ones((3,4,5,6)) # matriz de matrices de unos
b = np.rollaxis(a, 3, 1).shape

c= np.rollaxis(a, 2).shape

d= np.rollaxis(a, 1, 4).shape


print(b)
print(c)
print(d)

(3, 6, 4, 5)
(5, 3, 4, 6)
(3, 5, 6, 4)


In [174]:
"""
34 
numpy.swapaxes 
Intercambie dos ejes de una matriz.
"""
a=np.swapaxes(x,0,2) 
a


array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [175]:

x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]]) # otra forma de realizar sin el comando
x


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [180]:
"""
35
ndarray.T
La matriz transpuesta.
"""

x =np.array([[1.,2.],[3.,4.]])
print(x)

print("................")

a=(x.T)
print(a)



[[1. 2.]
 [3. 4.]]
................
[[1. 3.]
 [2. 4.]]


## Cambio de número de dimensiones

In [185]:
"""
36 
numpy.atleast_1d
Convierta entradas en matrices con al menos una dimensión.
"""

x = np.arange(9.0).reshape(3,3)
a = np.atleast_1d(x)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [184]:
"""
37 
numpy.atleast_2d
Ver entradas como matrices con al menos dos dimensiones.
"""

x = np.arange(3.0)
a = np.atleast_2d(x)
a

array([[0., 1., 2.]])

In [186]:
"""
38 
Ver entradas como matrices con al menos tres dimensiones.
"""

x = np.arange(12.0).reshape(4,3)
a = np.atleast_3d(x).shape
print(a)
print(".................")

b=np.atleast_3d(x).base is x.base 
print(b)

(4, 3, 1)
.................
True


In [190]:
"""
39 
Agregar manualmente dos vectores, utilizando la transmisión:
"""

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out


array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [200]:
"""
40 
numpy.expand_dims( a , eje )

Expande la forma de una matriz.
Inserte un nuevo eje que aparecerá en la posición del eje en la forma de matriz expandida.
"""

x = np.array(([4, 5, 6],[3,6,7]))
print(x)
print(".....................")

y = np.expand_dims(x, axis=1)
print(y)

[[4 5 6]
 [3 6 7]]
.....................
[[[4 5 6]]

 [[3 6 7]]]


In [201]:
"""
41 
numpy.squeeze( a , axis = None ) 
Eliminar entradas unidimensionales de la forma de una matriz.
"""

x = np.array([[[0], [1], [2]]])
y= np.squeeze(x, axis=0).shape 
print(y)

(3, 1)


## Cambiar el tipo de Matriz

In [207]:
"""
42 
numpy.asarray( a , dtype = None , order = None ) 
Convierta la entrada a una matriz.
"""
a = np.array([1, 2], dtype=np.float32)
b = np.asarray(a, dtype=np.float32) 
print(b)

[1. 2.]


In [208]:
"""
43 
numpy.asmatrix( datos , dtype = Ninguno ) 
Interprete la entrada como una matriz.
"""
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m



matrix([[5, 2],
        [3, 4]])

In [210]:
"""
43 
numpy.asmatrix( datos , dtype = Ninguno) 
Interprete la entrada como una matriz.
"""
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c=np.concatenate((a, b), axis=0)
print(c)
print(".............")
d= np.concatenate((a, b.T), axis=1)
print(d)

[[1 2]
 [3 4]
 [5 6]]
.............
[[1 2 5]
 [3 4 6]]


In [222]:
"""
44 
numpy.stack( arrays , axis = 0 , out = None )
Unir una secuencia de matrices a lo largo de un nuevo eje.
"""

arrays = [np.random.randn(3, 4) for _ in range(10)]
a = np.stack(arrays, axis=1).shape
(10, 3, 4)

(10, 3, 4)

In [217]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.stack((a, b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [225]:
"""
45 
numpy.hstack( tup )
Apile las matrices en secuencia horizontalmente (en sentido de columna).
"""

a = np.array((1,2,3))
b = np.array((2,3,4))
c= np.hstack((a,b))
c

array([1, 2, 3, 2, 3, 4])

In [228]:
"""
46 
numpy.hstack( tup )
Apile las matrices en secuencia horizontalmente (en sentido de columna).
"""

a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
c= np.hstack((a,b))
c

array([[1, 2],
       [2, 3],
       [3, 4]])

In [7]:
"""
47 
numpy.vstack( tup )
Apile las matrices en secuencia verticalmente (en sentido de fila).
"""
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c=np.vstack((a,b))
c



array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
c=np.vstack((a,b))
c

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [9]:
"""
48 
numpy.block( matrices )
Ensamble un nd-array a partir de listas anidadas de bloques.

Los bloques en las listas más internas se concatenan (ver concatenate) a lo 
largo de la última dimensión (-1), luego se concatenan a lo largo de la penúltima 
dimensión (-2), y así sucesivamente hasta que se alcanza la lista más externa.
"""

A = np.ones((2, 2), int)
B = 2 * A
c= np.block([[A], [B]])             
c


array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

## División de matrices 

In [15]:
"""
49
numpy.split ( ary , indices_or_sections , axis = 0 )
Dividir una matriz en múltiples sub-matrices como vistas en aria .
"""

x = np.arange(8.0)
c= np.split(x, [3, 5, 6, 10])
c

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [16]:
"""
50
numpy.array_split( ary , indices_or_sections , axis = 0 ) 
Dividir una matriz en múltiples sub-matrices.
"""

x = np.arange(7.0)
c= np.array_split(x, 3)
c

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

In [22]:
"""
51
numpy.dsplit( ary , indices_or_sections ) 
Dividir la matriz en múltiples sub-matrices a lo largo del 3er eje (profundidad).
"""

x = np.arange(16.0).reshape(2, 2, 4)
print(x)

print("..................")

c=np.dsplit(x, np.array([3, 6]))
print(c)


[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
..................
[array([[[ 0.,  1.,  2.],
        [ 4.,  5.,  6.]],

       [[ 8.,  9., 10.],
        [12., 13., 14.]]]), array([[[ 3.],
        [ 7.]],

       [[11.],
        [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]


In [23]:
"""
52
numpy.hsplit( ary , indices_or_sections ) 
Dividir una matriz en múltiples sub-matrices horizontalmente (en forma de columna).
"""
x = np.arange(8.0).reshape(2, 2, 2)
c=np.hsplit(x, 2)
c

[array([[[0., 1.]],
 
        [[4., 5.]]]), array([[[2., 3.]],
 
        [[6., 7.]]])]

## Arreglos de mosaico

In [32]:
"""
53
numpy.repeat( a , repeticiones , eje = Ninguno ) 
Repita elementos de una matriz.
"""

a=np.repeat(3, 4)
print(a) 

print("...............")

x = np.array([[1,2],[3,4],[5,6],[7,8]])
c=np.repeat(x, 2)
print(c)

[3 3 3 3]
...............
[ 1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11 12 12]


## Agregar y eliminar elementos 

In [29]:
"""
54
umpy.delete( arr , obj , axis = None ) 
Devuelve una nueva matriz con sub-matrices a lo largo de un eje eliminado. 
Para una matriz unidimensional, esto devuelve las entradas no devueltas por arr [obj] .
"""

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
c = np.delete(arr, np.s_[::2], 1)
c

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [35]:
"""
55
numpy.array_split( ary , indices_or_sections , axis = 0 ) 
Dividir una matriz en múltiples sub-matrices.
"""

x = np.arange(8.0)
print(x)

print("..............")

c = np.array_split(x, 3)
print(c)

[0. 1. 2. 3. 4. 5. 6. 7.]
..............
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]


In [41]:
"""
56
numpy.insert( arr , obj , valores , eje = Ninguno ) 
Insertar valores a lo largo del eje dado antes de los índices dados.
"""

a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)

print("...........")

c = np.insert(a, 1, 5)
print(c)

print("...........")

d= np.insert(a, 1, 5, axis=1)
print(d)

[[1 1]
 [2 2]
 [3 3]]
...........
[1 5 1 2 2 3 3]
...........
[[1 5 1]
 [2 5 2]
 [3 5 3]]


In [43]:
"""
57
numpy.append( arr , valores , eje = Ninguno ) 
Agregar valores al final de una matriz.
"""

c= np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
"""
58
numpy.resize( a , new_shape ) 
Devuelve una nueva matriz con la forma especificada.
"""
a=np.array([[0,1],[2,3]])
print(a)
print("...........")

b= np.resize(a,(1,4))
print(b)
print("...........")

c= np.resize(a,(2,4))
print(c)


[[0 1]
 [2 3]]
...........
[[0 1 2 3]]
...........
[[0 1 2 3]
 [0 1 2 3]]


In [45]:
"""
59 
numpy.trim_zeros( filt , trim = 'fb' )
Recorte los ceros iniciales y / o finales de una matriz o secuencia 1-D.
"""

a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
b = np.trim_zeros([0, 1, 2, 0])
print(b)

[1, 2]


In [46]:
"""
60
numpy.unique
Encuentra los elementos únicos de una matriz.
"""

a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
u

array([1, 2, 3, 4, 6])

## Reorganizando elementos 

In [48]:
"""
61
numpy.flip( m , eje = Ninguno )
Invierta el orden de los elementos en una matriz a lo largo del eje dado.
La forma de la matriz se conserva, pero los elementos se reordenan.
"""

A = np.arange(8).reshape((2,2,2))
print(A)
print("...........")

b=np.flip(A, 1)
print(b)
print("...........")

c= np.flip(A)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
...........
[[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]
...........
[[[7 6]
  [5 4]]

 [[3 2]
  [1 0]]]


In [53]:
"""
62
numpy.reshape
Da una nueva forma a una matriz sin cambiar sus datos.
"""

a = np.array([[1,2,3], [4,5,6]])
b = np.reshape(a, 6)
print(b)

print("...........")

c = np.reshape(a, (3,-1))
print(c)

[1 2 3 4 5 6]
...........
[[1 2]
 [3 4]
 [5 6]]


In [54]:
"""
63
numpy.roll( a , shift , axis = None ) 
Roll elementos de la matriz a lo largo de un eje dado.
Los elementos que ruedan más allá de la última posición se reintroducen en la primera.
"""

x = np.arange(10)
a = np.roll(x, 2)
a

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
"""
64
numpy.char.capitalize( a ) 
Devuelva una copia de a con solo el primer carácter de cada elemento en mayúscula.
"""
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c


array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [56]:
"""
65
numpy.char.decode
El conjunto de códecs disponibles proviene de la biblioteca estándar de Python y puede 
ampliarse en tiempo de ejecución. Para más información, vea el codecsmódulo.
"""

c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

## Información de la cadena

In [59]:
"""
66
numpy.char.count( a , sub , inicio = 0 , final = Ninguno ) 
Devuelve una matriz con el número de ocurrencias no superpuestas de subcadena sub en el rango [ inicio , fin ].
"""
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
a = np.char.count(c, 'A', start=1, end=4)
a

array([2, 1, 1])

In [61]:
"""
67
numpy.char.endswith( a , sufijo , inicio = 0 , final = Ninguno ) 
Devuelve una matriz booleana que es verdadera , donde el elemento de cadena en un extremo con el sufijo, 
de lo contrario falso .
"""
s = np.array(['foo', 'bar'])
s[0] = 'foo'
s[1] = 'bar'
s

array(['foo', 'bar'], dtype='<U3')

In [63]:
"""
68 
numpy.char.chararray
(shape , itemsize = 1 , unicode = False , buffer = None , offset = 0 , strides = None , order = None) 
Proporciona una vista conveniente de las matrices de cadenas y valores unicode.
"""

charar = np.chararray((3, 3))
charar[:] = 'a'
charar

chararray([[b'a', b'a', b'a'],
           [b'a', b'a', b'a'],
           [b'a', b'a', b'a']], dtype='|S1')

In [65]:
"""
69
numpy.char.compare_chararrays( a , b , cmp_op , rstrip ) 
Realiza una comparación entre elementos de dos matrices de 
cadenas utilizando el operador de comparación especificado por cmp_op .
"""

a = np.array(["a", "b", "cde"])
b = np.array(["a", "a", "dec"])
c = np.compare_chararrays(a, b, ">", True)
c

array([False,  True, False])

In [67]:
"""
70
numpy.shape 
numpy.shape( a ) 
Devuelve la forma de una matriz.
"""

a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
b =  np.shape(a)
b

(2,)

## Crear matrices de registros ( numpy.rec) 

In [68]:
"""
71
numpy.core.records.fromarrays
Crear una matriz de registros a partir de una lista (plana) de matrices
"""

x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)


In [70]:
"""
72
numpy.core.records.fromrecords
crear un recarray de una lista de registros en forma de texto
"""

r=np.core.records.fromrecords([(456,'dbe',1.2),(2,'de',1.3)],names='col1,col2,col3')
print(r[0])

(456, 'dbe', 1.2)


In [77]:
"""
73
numpy.vander( x , N = Ninguno , creciente = Falso ) 
Genera una matriz de Vandermonde.
"""

x = np.array([1, 2, 3, 5])
a = np.vander(x)
a

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [78]:
b= np.vander(x, increasing=True)
b

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])